str_to_vid/converter/urls.py
from django.urls import path

from converter.apps import ConverterConfig
from converter.views import download_video, index, VideoListView

app_name = ConverterConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('download/<int:pk>/', download_video, name='download_video'),
    path('videos/', VideoListView.as_view(), name='videos'),
]

str_to_vid/str_to_vid/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('converter.urls', namespace='converter')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

str_to_vid/converter/models.py
from django.db import models


class Video(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    message = models.TextField(verbose_name='Сообщение')
    video = models.FileField(upload_to='videos/', verbose_name='Видео')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

str_to_vid/converter/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

from converter.models import Video
from helpers.helpers import create_video_from_message, conversion_to_h264


@csrf_exempt
def index(request):
    # catches POST requests
    if request.method == 'POST':
        message = str(request.POST.get('message', ''))
        output = create_video_from_message(message)
        # conversion_to_h264(f'media/{output["path"]}')
        new_video = Video(title=output['title'], message=message, video=output['path'])
        new_video.save()
        context = {'object': new_video}
        return render(request, 'converter/index.html', context)
    # otherwise just shows page
    else:
        context = {}
        return render(request, 'converter/index.html', context)


def download_video(request, pk):
    video = Video.objects.get(pk=pk)
    response = HttpResponse(video.video, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename="{video.video.name}"'
    return response


class VideoListView(ListView):
    model = Video

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        print(queryset)
        return queryset

str_to_vid/converter/templates/converter/index.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="http://localhost:8000/">
  <label>Введите текст для видео:</label>
  <input type="text" name="message">
</form>
<br>
{% if object %}
Видео: {{ object.title}}  <a href="{% url 'converter:download_video' object.pk %}">Скачать</a>
{% endif %}
<br>
<a href="{% url 'converter:videos' %}">Все видео</a>
</body>
</html>

str_to_vid/converter/templates/converter/video_list.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object_list %}
    {% for object in object_list %}
        Видео: {{ object.title}}  <a href="{% url 'converter:download_video' object.pk %}">Скачать</a>
        <br>
    {% endfor %}
{% else %}
Список видео пуст
{% endif %}

</body>
</html>